name: Probe

on:
  push:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actions-executes at $(date -u +%FT%:%TZ)"
      - run: echo "runner=\$RUNNER_NAME os=\$ImageOS"
